### ISSUE TITLE
feat: Add autofix workflow

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/copier-uv#2]
```yaml
name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

env:
  PYTHON_VERSIONS: ""

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          make setup
          make format
      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
```
